esphome:
  name: pico-w-havuz-1
  friendly_name: pico-w-havuz-1

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ZjPD3Pv+EdFQY8hSqjrvz74cjvOFhwGJuVbQl7BFUws="

ota:
  - platform: esphome
    password: "53a0cdacb95c8c258f45c3124d1d9d50"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pico-W-Havuz-1 Fallback Hotspot"
    password: "JmDOPSVV3LGe"

one_wire:
  - platform: gpio
    pin: GPIO03 #pin 5

sensor:
  - platform: dallas_temp
    address: 0xb55b1dd446247f28
    name: "Su Sicakligi Sensoru"
    update_interval: 60s

  - platform: dht
    pin: GPIO04 #pin 6
    temperature:
      name: "DHT22 Sicaklik"
      id: dht22_temperature
      unit_of_measurement: "°C"
    humidity:
      name: "DHT22 Nem"
      id: dht22_humidity
      unit_of_measurement: "%"
    update_interval: 60s

  - platform: ultrasonic
    trigger_pin: GPIO16  # Pin 21
    echo_pin: GPIO17  # Pin 22
    name: "Havuzdaki Su Seviyesi"
    id: ultrasonik_mesafe
    update_interval: 60s
    unit_of_measurement: "cm"
    filters:
    - lambda: |-
        float mesafe = x * 100;
        const float havuz_boy = 27.0;
        if (mesafe > 0) {return havuz_boy - mesafe;}
        else {return 0;}

  - platform: adc
    pin: GPIO26  # Pin numarası
    name: "Bulaniklik Sensoru"
    id: bulaniklik_sensoru
    unit_of_measurement: "NTU"
    update_interval: 60s
      
  - platform: adc
    pin: GPIO27  # pin 32
    name: "pH Sensoru"
    unit_of_measurement: "pH"
    update_interval: 60s
    filters:
    - calibrate_linear:
       - 0.33 -> 4.01  
       - 1.65 -> 7.01  
       - 2.77 -> 10.01  
       
switch:
  - platform: gpio
    pin: GPIO00  # pin 1
    id: motor_relay_tahliye
    name: "Su Tahliye Motoru"
    inverted: True

  - platform: gpio
    pin: GPIO01  # pin 2
    id: motor_relay_hava
    name: "Hava Motoru"
    inverted: True       

  - platform: gpio
    pin: GPIO02  # pin 4
    id: motor_relay_filtreleme
    name: "Filtreleme Motoru"
    inverted: True

  - platform: gpio
    pin: GPIO05  # pin 7
    id: motor_relay_yemleme
    name: "Yemleme Motoru"
    inverted: True       